/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_MOTORCYCLESERVER_H_
#define JSONRPC_CPP_STUB_MOTORCYCLESERVER_H_

#include <jsonrpccpp/server.h>

class motorcycleServer : public jsonrpc::AbstractServer<motorcycleServer>
{
    public:
        motorcycleServer(jsonrpc::AbstractServerConnector &conn, jsonrpc::serverVersion_t type = jsonrpc::JSONRPC_SERVER_V2) : jsonrpc::AbstractServer<motorcycleServer>(conn, type)
        {
            this->bindAndAddMethod(jsonrpc::Procedure("alert", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT, "action",jsonrpc::JSON_STRING,"class_id",jsonrpc::JSON_STRING,"object_id",jsonrpc::JSON_STRING, NULL), &motorcycleServer::alertI);
        }

        inline virtual void alertI(const Json::Value &request, Json::Value &response)
        {
            response = this->alert(request["action"].asString(), request["class_id"].asString(), request["object_id"].asString());
        }
        virtual Json::Value alert(const std::string& action, const std::string& class_id, const std::string& object_id) = 0;
};

#endif //JSONRPC_CPP_STUB_MOTORCYCLESERVER_H_
